// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0kCk9sJi8iljWtoPTQnmYtUsZ8_SeCNk',
    appId: '1:372744722495:web:99ac714cd56c7a5aa6008a',
    messagingSenderId: '372744722495',
    projectId: 'finalproject-d7e5b',
    authDomain: 'finalproject-d7e5b.firebaseapp.com',
    storageBucket: 'finalproject-d7e5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4wSUb2d-RFd_MFmG0k0tx6DsHsgv5-m8',
    appId: '1:372744722495:android:3972c709fcdf4320a6008a',
    messagingSenderId: '372744722495',
    projectId: 'finalproject-d7e5b',
    storageBucket: 'finalproject-d7e5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiG99OndrPxH1ZJnwpoXdRVldO0oGYszM',
    appId: '1:372744722495:ios:8cf36c0d3b0d9223a6008a',
    messagingSenderId: '372744722495',
    projectId: 'finalproject-d7e5b',
    storageBucket: 'finalproject-d7e5b.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiG99OndrPxH1ZJnwpoXdRVldO0oGYszM',
    appId: '1:372744722495:ios:8cf36c0d3b0d9223a6008a',
    messagingSenderId: '372744722495',
    projectId: 'finalproject-d7e5b',
    storageBucket: 'finalproject-d7e5b.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );
}
